# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 763989562119a9b411cfd72e61db70e7302bd3c82b65a176372a3483b523ab8bd6675cb4f55d26fa6921600519620325d3009f5cfacec9a0cd29abb6d15ffebc

test:
  secret_key_base: 17562c65968690a4ab14d710b5e8f04e9873857a22201f5cb71e2a6c81c673dff8fb4e474a0c69559539fd447a26442e56dabb7ee117668e3c02712b16ef1962

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
