# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.create! name: "Amateur"
Category.create! name: "Anal"
Category.create! name: "Arab"
Category.create! name: "Asian"
Category.create! name: "Babe"
Category.create! name: "Babysitter"
Category.create! name: "Big Ass"
Category.create! name: "Big Dick"
Category.create! name: "Big Tits"
Category.create! name: "Blonde"
Category.create! name: "Blowjob"
Category.create! name: "Bondage"
Category.create! name: "British"
Category.create! name: "Brunette"
Category.create! name: "Bukkake"
Category.create! name: "Cartoon"
Category.create! name: "Casting"
Category.create! name: "Celebrity"
Category.create! name: "College"
Category.create! name: "Compilation"
Category.create! name: "Creampie"
Category.create! name: "Cumshots"
Category.create! name: "Double Penetration"
Category.create! name: "Ebony"
Category.create! name: "Euro"
Category.create! name: "Feet"
Category.create! name: "Fetish"
Category.create! name: "Fisting"
Category.create! name: "For Women"
Category.create! name: "French"
Category.create! name: "Gangbang"
Category.create! name: "German"
Category.create! name: "Handjob"
Category.create! name: "Hardcore"
Category.create! name: "Indian"
Category.create! name: "Interracial"
Category.create! name: "Italian"
Category.create! name: "Japanese"
Category.create! name: "Korean"
Category.create! name: "Latina"
Category.create! name: "Lesbian"
Category.create! name: "Massage"
Category.create! name: "Masturbation"
Category.create! name: "Mature"
Category.create! name: "MILF"
Category.create! name: "Orgy"
Category.create! name: "Party"
Category.create! name: "Pornstar"
Category.create! name: "POV"
Category.create! name: "Public"
Category.create! name: "Pussy Licking"
Category.create! name: "Reality"
Category.create! name: "Red Head"
Category.create! name: "Rough Sex"
Category.create! name: "Russian"
Category.create! name: "School"
Category.create! name: "Small Tits"
Category.create! name: "Smoking"
Category.create! name: "Squirt"
Category.create! name: "Striptease"
Category.create! name: "Teen"
Category.create! name: "Threesome"
Category.create! name: "Toys"
Category.create! name: "Uniform"
Category.create! name: "Webcam"



admin = User.create! :email => 'admin123333412542@admin.com', :password => 'topsecret', :password_confirmation => 'topsecret'
admin.update_attribute :admin, true